# Weights and biases
wandb_run: False

# Directory structure
base_dir: 'C:\Users\Ian Hill\PycharmProjects\CPSC532W\cpsc532w\HW4' # NOTE: This path should be relative to the daphne path!
daphne_dir: '..\..\daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
HW4_programs: [4]
#HW4_programs: [1, 2, 3, 4, 5]

# Daphne (re)compilation
compile: False

# Evaluation method
mode: 'VI'

# Inference
num_samples: 1e2