# Weights and biases
wandb_run: False

# Directory structure
base_dir: 'C:\Users\Ian Hill\PycharmProjects\CPSC532W\cpsc532w\HW3' # NOTE: This path should be relative to the daphne path!
daphne_dir: '..\..\daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
HW3_programs: [1, 2, 3, 4, 5]

# Daphne (re)compilation
compile: False

# Evaluation method
#mode: 'IS'
#mode: 'MHG'
mode: 'HMC'

# Inference
num_samples: 1e1